### ISSUE TITLE
Les cotisations ne sonts pas mises à jour lorsqu'un utilisateur est ajouté ou modifié.

### ISSUE THREAD

**Issue by Alabate** [buckutt/contributor-updater#1]
Quand un utilisateur est créé ou un meansoflogin modifié ou ajouté, le script plante avec l'erreur suivante au moment de l'update de la cotisation.
 ```
TypeError: Cannot read property 'contributor' of undefined
    at buckuttMembers.forEach (/home/buckutt/contributor-updater/main.js:136:31)
    at Array.forEach (native)
    at axios.post.then.then.then.then (/home/buckutt/contributor-updater/main.js:135:24)
```

Sauf erreur de ma part, ça vient de la ligne 132
```
buckuttMembers = buckuttMembers.concat(usersCreated);
```
qui vient ajouter le retour des promises (et donc les nouveaux utilisateurs) au `buckuttMembers` qui est ensuite analysé pour mettre à jour les cotisations. Sauf que `buckuttMembers` ne contient pas une simple liste d'utilisateur, mais une liste formaté par la ligne 40. Donc erreur parce que le format n'est pas le bon.

La conséquence, c'est que lors d'une première passe avec modification des utilisateurs (modification de meansOfLogins ou ajout d'user), les cotisations ne sont pas mis à jour parce que ça plante juste avant. Par contre si on rééxecute juste après, les modifications utilisateurs ont été faites et du coup les cotisations sont mises à jour puisqu'ils n'y a rien de concaténé à `buckuttMembers`.

**Comment by lonk** [comment]
Fixed by bae5ce323168d197fabccf47db9980fa0192ad1a
